# Site settings
title: syslog # site title
description: >- # site description
  A log of the hacking I do in my spare time. Might
  contain poor code and rants about computer science.
lang: en-US # default lang
timezone: America/Sao_Paulo # set your timezone
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Pietro Carrara # author name
  username: arnett # author username
  github: PietroCarrara
  # twitter: twitter_username
  # facebook: facebook_username
  email: pbcarrara@inf.ufrgs.br # your contact adress
  avatar: /assets/img/avatar.png # change with your own avatar

# Url settings
url: "https://pietrocarrara.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
