# disablePathToLower: true
baseURL: https://pietrocarrara.github.io
theme: m10c
defaultContentLanguage: en
title: syslog

languages:
  en:
    params:
      description: Personal blog where I write about anything. From movie reviews to my tech problems.
  pt-br:
    params:
      description: Blog pessoal onde eu escrevo sobre tudo. De reviews de filmes a meus problemas técnicos.

menu:
  main:
    -
      identifier: posts
      name: Posts
      url: /posts/
    -
      identifier: tags
      name: Tags
      url: /tags/

params:
  menu_item_separator: " | "
  author: Pietro Carrara
  avatar: /img/avatar.jpg

  lang_text:
      en: 🇺🇸
      pt-br: 🇧🇷

  social:
    -
      icon: github
      name: Github
      url: https://github.com/PietroCarrara
    -
      icon: film
      name: TheMovieDB
      url: https://www.themoviedb.org/u/piticarrara

# Fix aac not being recognized as audio
mediaTypes:
  "audio/aac":
    suffixes:
      - "aac"