# disablePathToLower: true
baseURL: https://pietrocarrara.github.io
theme: m10c
defaultContentLanguage: pt-br
title: syslog
timeout: 60000

languages:
  pt-br:
    weight: 1
    params:
      description: Blog pessoal onde eu escrevo sobre tudo. De reviews de filmes a meus problemas técnicos.
  en:
    weight: 2
    params:
      description: Personal blog where I write about anything. From movie reviews to my tech problems.

menu:
  main:
    -
      identifier: posts
      name: Posts
      url: /posts/
    -
      identifier: tags
      name: Tags
      url: /tags/

params:
  menu_item_separator: " | "
  author: Pietro Carrara
  social:
    -
      icon: github
      name: Github
      url: https://github.com/PietroCarrara
    -
      icon: film
      name: TheMovieDB
      url: https://www.themoviedb.org/u/piticarrara
    -
      icon: book-open
      name: GoodReads
      url: https://www.goodreads.com/user/show/52352747-pietro-carrara

# Fix aac not being recognized as audio
mediaTypes:
  "audio/aac":
    suffixes:
      - "aac"

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: true

enableRobotsTXT: true
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
