# disablePathToLower: true
baseURL: https://pietrocarrara.github.io
theme: m10c
defaultContentLanguage: pt-br
title: syslog
timeout: 60000

languages:
  pt-br:
    LanguageName: Português Brasileiro
    weight: 1
    params:
      description: Blog pessoal onde eu escrevo sobre tudo. De reviews de filmes a meus problemas técnicos.
  en:
    LanguageName: English
    weight: 2
    params:
      description: Personal blog where I write about anything. From movie reviews to my tech problems.

menu:
  main:
    -
      identifier: posts
      name: Posts
      url: /posts/
    -
      identifier: tags
      name: Tags
      url: /tags/

params:
  menu_item_separator: " | "
  author: Pietro Carrara
  title: syslog
  fb_app_id: 342520437942701
  social:
    -
      icon: github
      name: Github
      url: https://github.com/PietroCarrara
    -
      icon: twitter
      name: Mastodon
      url: https://dice.camp/@tanuko
    -
      icon: film
      name: TheMovieDB
      url: https://www.themoviedb.org/u/piticarrara
    -
      icon: book-open
      name: BookWyrm
      url: https://velhaestante.com.br/user/tanuko
  robots:
    disable:
      - /vanderbei-linear-programming-book/
      - /InterPong/
      - /Padoru/

# Fix aac not being recognized as audio
mediaTypes:
  "audio/aac":
    suffixes:
      - "aac"

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepQuotes: true
      keepWhitespace: true

enableGitInfo: true

enableRobotsTXT: true
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
